name: tests
on: [push, pull_request]

jobs:
  ci:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest]   
    name: CI
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: go fmt ./...
      - run: go test -race ./...
      - run: go test -v ./...
